### ISSUE TITLE
API break from cb1ab5fc8b993f23924385ebee42d52ff45e4e8a

### ISSUE THREAD

**Issue by cgwalters** [jpirko/libndp#9]
This broke NetworkManager: http://build.gnome.org/continuous/buildmaster/builds/2016/03/10/21/build/log-NetworkManager.txt

For now I've "frozen" libndp: https://git.gnome.org/browse/gnome-continuous/commit/?id=8481fb467e1250b4c4a73237e091922e63dfaff5

**Comment by thom311** [comment]
Fixed by commit https://github.com/jpirko/libndp/commit/9be7e45d57d7c65d01c15819df0e864b25275dbe

**Comment by jpirko** [comment]
this is resolved by:

commit 9be7e45d57d7c65d01c15819df0e864b25275dbe
Author: Thomas Haller <thaller@redhat.com>
Date:   Thu Mar 10 11:55:54 2016 +0100

    libndp: revert API change for ndp_msg_send() and add ndp_msg_send_with_flags()
    
    Fixes: cb1ab5fc8b ("libndp: add option flags to send messages")
    Signed-off-by: Thomas Haller <thaller@redhat.com>
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
